apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca
  namespace: istio-system
spec:
  isCA: true
  duration: 87600h
  secretName: istio-ca
  commonName: istiod.bjdazure.tech
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - cert sign
  dnsNames:
    - istiod.bjdazure.tech
    - istiod.istio-system.svc
  subject:
    organizations:
    - bjdazure.tech
    - cluster.local
    - istio-system.svc
    - cert-manager
  issuerRef:
    name: vault-issuer
    kind: Issuer
    group: cert-manager.io