---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
    topology.istio.io/network: centralus
---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    istio-injection: enabled
---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  profile: default
  meshConfig:
    trustDomain: cluster.local
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    enablePrometheusMerge: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  values:
    global:
      meshID: examplemesh
      multiCluster:
        clusterName: default-cluster-name
      network: default-region
      caAddress: cert-manager-istio-csr.cert-manager.svc:443
  components:
    pilot:
      k8s:
        podDisruptionBudget:
          minAvailable: 1
        env:
        - name: ENABLE_CA_SERVER
          value: "false"
        overlays:
        - apiVersion: apps/v1
          kind: Deployment
          name: istiod
           # Needs proper path configuraion and validation #
          patches:
          - path: spec.template.spec.containers.[name:discovery].args[-1]
            value: "--tlsCertFile=/etc/cert-manager/tls/tls.crt"
          - path: spec.template.spec.containers.[name:discovery].args[-1]
            value: "--tlsKeyFile=/etc/cert-manager/tls/tls.key"
          - path: spec.template.spec.containers.[name:discovery].args[-1]
            value: "--caCertFile=/etc/cert-manager/ca/root-cert.pem"

          - path: spec.template.spec.containers.[name:discovery].volumeMounts[-1]
            value:
              name: cert-manager
              mountPath: "/etc/cert-manager/tls"
              readOnly: true
          - path: spec.template.spec.containers.[name:discovery].volumeMounts[-1]
            value:
              name: ca-root-cert
              mountPath: "/etc/cert-manager/ca"
              readOnly: true

          - path: spec.template.spec.volumes[-1]
            value:
              name: cert-manager
              secret:
                secretName: istiod-tls
          - path: spec.template.spec.volumes[-1]
            value:
              name: ca-root-cert
              configMap:
                defaultMode: 420
                name: istio-ca-root-cert
           # Needs proper path configuraion and validation #
    egressGateways:
    - name: istio-egressgateway
      namespace: istio-system
      enabled: true
      k8s:
        podDisruptionBudget:
          minAvailable: 1
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        istio: ingressgateway
        app: istio-ingressgateway 
        aadpodidbinding: default-pod-identity
      k8s:
        podDisruptionBudget:
          minAvailable: 1
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    - name: istio-eastwestgateway
      namespace: istio-system
      enabled: true
      label:
        istio: eastwestgateway
        app: istio-eastwestgateway
        topology.istio.io/network: default-region
      k8s:
        env:
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: default-region
        podDisruptionBudget:
          minAvailable: 1
        service:
          ports:
            - name: status-port
              port: 15021
              targetPort: 15021
            - name: tls
              port: 15443
              targetPort: 15443
            - name: tls-istiod
              port: 15012
              targetPort: 15012
            - name: tls-webhook
              port: 15017
              targetPort: 15017
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  addonComponents:
    prometheus:
      enabled: false
    kiali:
      enabled: false
    grafana:
      enabled: false