apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - certificate-issuer.yaml
  - certificate.yaml
  - istio-csr.yaml
  - istio-system.yaml
  - istio-default-ingress.yaml
  - istio-gateways.yaml