---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-controlplane
spec:
  values:
    global:
      multiCluster:
        clusterName: a212scus
      network: southcentralus
  components:
    ingressGateways:
    - name: istio-eastwestgateway
      label:
        topology.istio.io/network: southcentralus
      k8s:
        env:
        - name: ISTIO_META_REQUESTED_NETWORK_VIEW
          value: southcentralus