apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  template:
    metadata:
      labels:
        aadpodidbinding: a212scus-istio-pod-identity
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: otel-collector-config
spec:
  parameters:                                     
    keyvaultName: a212scus-kv