apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster-addons/istio-manifests/region
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istiod
      namespace: istio-system