apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-namespace.yaml
  - certificate-issuer.yaml
  - certificate.yaml
  - istio-system.yaml
  - istio-default-ingress.yaml
  - istio-gateways.yaml