apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - isti-operator.yaml
  - istio-namespace.yaml
  - certificate-issuer.yaml
  - certificate.yaml
  - istio-system.yaml
  - istio-default-ingress.yaml
  - istio-gateways.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.7.1
  releaseName: cert-manager
  namespace: cert-manager

- name: kured
  repo: https://weaveworks.github.io/kured
  version: v2.10.0
  releaseName: kured
  namespace:  kured-system

- name: cert-manager-istio-csr
  repo: https://charts.jetstack.io
  version: 'v0.5.0'
  releaseName: cert-manager-istio-csr
  namespace: cert-manager
  valuesInline:
    app:
      logLevel: 2
      server:
        clusterID: default-cluster-name
        maxCertificateDuration: 168h
      tls:
        istiodCertificateDuration: 168h
        certificateDuration: 24h
        certificateDNSNames: 
        - cert-manager-istio-csr.istio-system.svc
        rootCAFile: "/var/run/secrets/istio-csr/ca.crt"
      certmanager:
        issuer:
          name: "vault-issuer"
    volumeMounts:
    - name: "root-ca"
      mountPath: "/var/run/secrets/istio-csr"
      readOnly: true
    volumes:
    - name: "root-ca"
      secret:
        secretName: "istio-ca"