apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - isti-operator.yaml
  - istio-namespace.yaml
  - certificate-issuer.yaml
  - certificate.yaml
  - istio-csr.yaml
  - istio-system.yaml
  - istio-default-ingress.yaml
  - istio-gateways.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v1.7.1
  releaseName: cert-manager
  namespace: cert-manager
  
- name: cert-manager
  repo: https://charts.jetstack.io
  version: v2.10.0
  releaseName: kured
  namespace:  kured-system