apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zipkin.yaml
  - container-azm-ms-agentconfig.yaml
  - istio-system.yaml
  - istio-gateway.yaml
  - istio-ingress-deployment.yaml