apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  path: ./cluster-addons/istio-manifests/southcentral
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: istio-gateway
  namespace: flux-system
spec:
  path: ./cluster-addons/istio-gateways/southcentral