apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-approle
  namespace: istio-system
data: 
  secretId: ""
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: istio-system
spec:
  vault:
    path: pki/sign/bjdazure-dot-tech
    namespace: admin
    server: ""
    auth:
      appRole:
        path: approle
        roleId: ""
        secretRef:
          name: cert-manager-vault-approle
          key: secretId