apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: opentelemetry
  template:
    metadata:
      labels:
        aadpodidbinding: g6258cus-istio-pod-identity
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: otel-collector-config
spec:
  parameters:                                     
    keyvaultName: g6258cus-kv                                     