apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-approle
  namespace: cert-manager
data:
  secretId: OTg1MzM2YzktODY2NS00OGIzLTkyMmYtYzdiMmRlMjE5MjEzCg==
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: cert-manger
spec:
  vault:
    path: pki_int/sign/bjdazure-tech
    server: https://bjdazuretech-vault.vault.f3a9ef81-a6ae-4b97-8997-f9afafd6992a.aws.hashicorp.cloud:8200
    auth:
      appRole:
        path: approle
        roleId: "02b241f0-21e9-4527-ad67-eba84675dcb4"
        secretRef:
          name: cert-manager-vault-approle
          key: secretId