---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cert-manager-vault-approle
  namespace: istio-system
data: 
  secretId: ""
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: istio-system
spec:
  vault:
    path: pki/sign/bjdazure-dot-tech
    namespace: admin
    server: https://bjdazuretech-vault.vault.f3a9ef81-a6ae-4b97-8997-f9afafd6992a.aws.hashicorp.cloud:8200
    auth:
      appRole:
        path: approle
        roleId: "371544b4-0115-501c-a059-59be95f8c02c"
        secretRef:
          name: cert-manager-vault-approle
          key: secretId