apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-intermediate-ca
  namespace: istio-system
spec:
  isCA: true
  duration: 87600h
  secretName: istio-intermediate-ca
  commonName: istio-intermediate-ca.bjdazure.tech
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - cert sign
  subject:
    organizations:
    - bjdazure.tech
    - cluster.local
    - cert-manager
  issuerRef:
    name: vault-issuer
    kind: Issuer
    group: cert-manager.io